version: "3"
services:
  etrobo-docker:
    image: korosuke613/etrobo-docker
    command: sleep infinity
    volumes:
      - ../:/home/hrp2/sdk/workspace/product
      - ~/.gitconfig:/root/.gitconfig
    environment:
      SHELL: "/bin/bash"
      HOME: "/home/hrp2"
